INCLUDE(FindPackageHandleStandardArgs)
IF(QT_SERIAL_PORT_LIBRARIES)
    SET(QtSerialPort_FIND_QUIETLY TRUE)
ENDIF(QT_SERIAL_PORT_LIBRARIES)

FIND_LIBRARY(QT_SERIAL_PORT_LIBRARIES
             QtSerialPort
             HINTS
             ${QT_LIBRARY_DIR}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(QtSerialPort DEFAULT_MSG QT_SERIAL_PORT_LIBRARIES)
MARK_AS_ADVANCED(QT_SERIAL_PORT_LIBRARIES)
